import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";

const onest = Onest({
	subsets: ["latin"],
	display: "swap",
	weight: ["400", "500", "700", "900"],
	variable: "--font-onest",
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${onest.variable}`}>
			<body className="font-sans">{children}</body>
		</html>
	);
}
