import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";

const onest = Onest({
	subsets: ["latin"],
	display: "swap",
	weight: ["400", "500", "700", "900"],
	variable: "--font-onest",
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${onest.variable}`}>
			<body className="typography-body-text-1 bg-gray_04 font-sans">
				<Header className="w-full py-[14px]  fixed left-1/2 transform -translate-x-1/2 z-10" />
				{children}
			</body>
		</html>
	);
}
